/* eslint-disable prettier/prettier */
export const BlendModes = {
	'source-over': 'source-over',
	'source-in': 'source-in',
	'source-out': 'source-out',
	'source-atop': 'source-atop',
	'destination-over': 'destination-over',
	'destination-in': 'destination-in',
	'destination-out': 'destination-out',
	'destination-atop': 'destination-atop',
	lighter: 'lighter',
	copy: 'copy',
	xor: 'xor',
	multiply: 'multiply',
	screen: 'screen',
	overlay: 'overlay',
	darken: 'darken',
	lighten: 'lighten',
	'color-dodge': 'color-dodge',
	'color-burn': 'color-burn',
	'hard-light': 'hard-light',
	'soft-light': 'soft-light',
	difference: 'difference',
	exclusion: 'exclusion',
	hue: 'hue',
	saturation: 'saturation',
	color: 'color',
	luminosity: 'luminosity',
} as const;
