const DisplayEvents = {
  SET_SCALE: 'DISPLAY_SET_SCALE',
  FULLSCREEN: 'DISPLAY_FULLSCREEN',
  UNFULLSCREEN: 'DISPLAY_UNFULLSCREEN',
  FOCUS: 'DISPLAY_FOCUS',
  BLUR: 'DISPLAY_BLUR',
};

export default DisplayEvents;
